import Link from "next/link";
import { fetchFeed, fetchRepoStats, formatStars } from "@/lib/github";
import { getDispatch, getEnv } from "@/lib/kv";
import { getFacts } from "@/lib/facts";
import { Ticker } from "@/components/ticker";
import { StatGrid } from "@/components/stat-grid";
import { Seal } from "@/components/seal";
import { InstallCodeBlock } from "@/components/install-code-block";
import { TerminalPlayer } from "@/components/terminal-player";
import type { CuratedDispatch, FeedItem, RepoStats } from "@/lib/types";

export const revalidate = 1800;

const FALLBACK_STATS: RepoStats = {
  stars: 0,
  forks: 0,
  openIssues: 0,
  openPulls: 0,
  contributors: 141,
  fetchedAt: new Date().toISOString(),
};

import { RELEASE_CONTRIBUTORS, RELEASE_HELPERS } from "@/lib/release-credits";

const FALLBACK_DISPATCH_EN: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "Quiet release week — install paths and contributor guides up to date.",
  summary:
    "This dispatch is regenerated by DeepSeek V4-Flash on a six-hour cron. Until the cron fills in fresh repo activity, the static links below are the best starting points.",
  highlights: [
    { title: "Install", href: "/en/install", tag: "shipped", blurb: "npm, Cargo, Homebrew, or a direct download." },
    { title: "Open issues", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "Start with anything labelled good first issue." },
    { title: "Roadmap", href: "/en/roadmap", tag: "discussion", blurb: "What is confirmed, what is being weighed, what is ruled out." },
  ],
  movers: [],
};

const FALLBACK_DISPATCH_ZH: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "本周发布平稳——安装路径和贡献指南已同步。",
  summary:
    "本「今日要闻」由 DeepSeek V4-Flash 每六小时重新生成。在 cron 写入真实仓库动态之前，下面的固定链接是最实用的入口。",
  highlights: [
    { title: "安装", href: "/zh/install", tag: "shipped", blurb: "npm、Cargo、Homebrew，或直接下载。" },
    { title: "开放议题", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "从 good first issue 标签开始。" },
    { title: "路线图", href: "/zh/roadmap", tag: "discussion", blurb: "已确认、审议中、以及已排除的功能。" },
  ],
  movers: [],
};

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";
  const env = await getEnv();
  const facts = await getFacts();

  let stats: RepoStats = FALLBACK_STATS;
  let feed: FeedItem[] = [];
  let dispatch: CuratedDispatch = isZh ? FALLBACK_DISPATCH_ZH : FALLBACK_DISPATCH_EN;

  try {
    [stats, feed] = await Promise.all([
      fetchRepoStats(env.GITHUB_TOKEN),
      fetchFeed(env.GITHUB_TOKEN, 12),
    ]);
  } catch (e) {
    console.error("github fetch failed", e);
  }

  try {
    const cached = await getDispatch();
    if (cached) dispatch = cached;
  } catch {
    /* keep fallback */
  }

  const highlights = isZh && dispatch.highlightsZh ? dispatch.highlightsZh : dispatch.highlights;

  return (
    <>
      {/* HERO — the claim, with the proof beside it */}
      <section className="relative">
        <div className="mx-auto max-w-[1400px] px-4 sm:px-6 pt-10 sm:pt-14 pb-12 grid lg:grid-cols-12 gap-10 lg:items-start">
          <div className="lg:col-span-7">
            <div className="mb-6">
              <span className="pill pill-hot">{isZh ? "开源 · 任意模型 · 运行在你的终端" : "Open source · Any model · Runs in your terminal"}</span>
            </div>

            <h1 className="font-display tracking-crisp">
              {isZh
                ? "编码智能体运行在代码之上。CodeWhale 还运行在法典之上。"
                : "Coding agents run on code. CodeWhale also runs on law."}
            </h1>

            <p className="mt-6 text-lg text-ink-soft leading-relaxed max-w-2xl">
              <span className="font-cjk text-indigo font-semibold">CodeWhale</span>
              {isZh
                ? " 是一个开源的终端编程智能体——一个 TUI，一个 CLI——适配任意模型，DeepSeek 与开放权重模型享有一级支持。指令总在堆积、彼此冲突：过时的规格、陈旧的交接、你此刻的要求、刚跑出的测试结果。多数智能体靠猜来化解；CodeWhale 靠位阶来裁决——一部嵌套的宪法：内置的基础法、你的常备规则、仓库自己的法。由执行框架强制生效，换掉模型也不失效。"
                : " is an open-source terminal coding agent — a TUI and a CLI — for any model, with DeepSeek and open weights first-class. Instructions pile up and conflict: the old spec, a stale handoff, your request, fresh test output. Most agents resolve that by guess. CodeWhale resolves it by rank — a nested constitution: bundled base law, your standing rules, your repo's own law. Enforced in the harness, intact when you swap models."}
            </p>

            <div className="mt-7 flex flex-wrap items-stretch sm:items-center gap-3">
              <Link
                href={isZh ? "/zh/install" : "/install"}
                className="flex-1 sm:flex-none text-center px-5 py-3 bg-ink text-paper font-mono text-sm uppercase tracking-wider hover:bg-indigo transition-colors"
              >
                {isZh ? "安装 →" : "Install →"}
              </Link>
              <Link
                href={isZh ? "/zh/docs/constitution" : "/docs/constitution"}
                className="flex-1 sm:flex-none text-center px-5 py-3 hairline-t hairline-b hairline-l hairline-r font-mono text-sm uppercase tracking-wider hover:bg-paper-deep transition-colors"
              >
                {isZh ? "阅读宪法 →" : "Read the constitution →"}
              </Link>
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="px-5 py-3 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors"
                aria-label={isZh ? "GitHub 星标" : "GitHub stars"}
              >
                ★ {stats.stars > 0 ? `${formatStars(stats.stars)} · GitHub` : "GitHub"}
              </Link>
            </div>

            <div className="mt-7 max-w-xl">
              <div className="eyebrow mb-2">{isZh ? "一行安装" : "one-line install"}</div>
              <InstallCodeBlock
                cmd="npm install -g codewhale"
                copyLabel={isZh ? "复制" : "Copy"}
                copiedLabel={isZh ? "已复制 ✓" : "Copied ✓"}
              />
              <div className="mt-2 flex items-center justify-between gap-3 text-[0.7rem] font-mono text-ink-mute flex-wrap">
                <span>{isZh ? "需要 Node 18+，无需 Rust 工具链" : "needs Node 18+ — no Rust toolchain"}</span>
                <Link href={isZh ? "/zh/install" : "/install"} className="text-indigo hover:underline">
                  {isZh ? "其他方式（Cargo / Homebrew / 国内镜像）→" : "other ways (Cargo / Homebrew / mirrors) →"}
                </Link>
              </div>
            </div>

            <div className="mt-6 flex items-center gap-4 text-xs font-mono text-ink-mute flex-wrap">
              <span>{isZh ? "由 Hmbown 维护" : "Maintained by Hmbown"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.version ? `v${facts.version}` : "v0.8.x"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.providers.length} {isZh ? "个提供商" : "providers"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.license ?? "MIT"}</span>
            </div>
          </div>

          {/* SEE HOW IT DECIDES — real traces, typed into a terminal pane */}
          <div className="lg:col-span-5">
            <div className="eyebrow mb-3">{isZh ? "看它如何裁决" : "See how it decides"}</div>
            <TerminalPlayer locale={locale} />
            <p className="mt-3 text-xs text-ink-mute leading-relaxed">
              {isZh
                ? "摘自真实会话的忠实片段——宪法可以在模型的推理里被直接观察到，而不是落地页上的一句宣称。"
                : "Faithful excerpts from a real session — the constitution is observable in the model's reasoning, not a claim on a landing page."}
            </p>
          </div>
        </div>
      </section>

      {/* live repo activity — below the hero, above the numbers */}
      <Ticker items={feed} />

      {/* THREE LAYERS OF LAW — the thesis in brief; the full page is /constitution */}
      <section className="mx-auto max-w-[1400px] px-6 py-12">
        <div className="flex flex-wrap items-baseline gap-x-4 gap-y-2 mb-6 hairline-b pb-4">
          <Seal char="法" />
          <h2 className="font-display">{isZh ? "三层法" : "Three layers of law"}</h2>
          <span className="pill pill-new">
            {isZh ? "v0.8.67 新增：宪法优先设置" : "New in v0.8.67: constitution-first setup"}
          </span>
        </div>

        <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
          {(isZh
            ? [
                { n: "01", t: "内置宪法", path: "编译进每一个二进制", d: "基础法。其中的位阶条款为一切冲突固定裁决顺序。" },
                { n: "02", t: "/constitution", path: "$CODEWHALE_HOME/constitution.json", d: "你的常备法——首次启动引导起草，模型可以代拟，由你批准，跨项目生效。" },
                { n: "03", t: "仓库自己的法", path: ".codewhale/constitution.json", d: "受保护的不变量、分支策略、验证要求、升级条件——位阶高于项目说明、记忆与交接。" },
              ]
            : [
                { n: "01", t: "Bundled Constitution", path: "compiled into every binary", d: "The base law. Its priority article fixes the authority order for any conflict." },
                { n: "02", t: "/constitution", path: "$CODEWHALE_HOME/constitution.json", d: "Your standing law — drafted at first launch with your model's help, ratified by you, carried across projects." },
                { n: "03", t: "Your repo's law", path: ".codewhale/constitution.json", d: "Protected invariants, branch policy, verification, escalation — above project instructions, memory, and handoffs." },
              ]
          ).map((item) => (
            <Link key={item.n} href={isZh ? "/zh/constitution" : "/constitution"} className="block p-6 hover:bg-paper-deep transition-colors">
              <div className="font-mono uppercase tracking-widest mb-2 text-[0.7rem] text-indigo">{item.n}</div>
              <h3 className="font-display text-xl mb-1">{item.t}</h3>
              <div className="font-mono text-[0.68rem] text-ink-mute mb-3 break-all">{item.path}</div>
              <p className={`text-sm text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {item.d}
              </p>
            </Link>
          ))}
        </div>

        <div className="mt-5 flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2">
          <p className="text-xs text-ink-mute leading-relaxed max-w-xl">
            {isZh
              ? "审批、沙箱、网络与信任控制由代码强制执行——宪法文本永远越不过它们。"
              : "Approval, sandbox, network, and trust controls are enforced in code — constitution text never overrides them."}
          </p>
          <Link
            href={isZh ? "/zh/constitution" : "/constitution"}
            className="font-mono text-xs uppercase tracking-widest text-indigo hover:underline"
          >
            {isZh ? "为什么是法 →" : "Why law →"}
          </Link>
        </div>
      </section>

      <StatGrid stats={stats} />

      {/* GET STARTED — the two or three steps, with the real links */}
      <section className="mx-auto max-w-[1400px] px-6 py-14">
        <div className="flex items-baseline gap-4 mb-2 hairline-b pb-4">
          <Seal char="起" />
          <h2 className="font-display">
            {isZh ? "怎么开始" : "Get started"}
          </h2>
        </div>
        <p className={`mb-8 text-ink-soft max-w-2xl ${isZh ? "leading-[1.9] tracking-wide" : "text-sm leading-relaxed"}`}>
          {isZh
            ? "三步：装好、配一个模型密钥、在项目里运行。每一步的细节都在安装指南里。"
            : "Three steps: install it, point it at a model key, and run it in a project. The install guide walks through each one."}
        </p>

        <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
          {(isZh
            ? [
                { n: "01", t: "安装", d: "npm 一行装好，或用 Cargo / Homebrew / 直接下载二进制。中国大陆网络有 CNB 与清华 Tuna 镜像。", cta: "安装指南 →", href: isZh ? "/zh/install" : "/install" },
                { n: "02", t: "配密钥", d: "codewhale auth set --provider deepseek（或 openrouter、anthropic、zai 等）。本地 vLLM / Ollama 无需密钥。", cta: "提供商列表 →", href: isZh ? "/zh/docs#providers" : "/docs#providers" },
                { n: "03", t: "运行", d: "在项目目录里敲 codewhale。默认 Plan 只读调查；按 Tab 切到 Agent 执行。", cta: "文档 →", href: isZh ? "/zh/docs" : "/docs" },
              ]
            : [
                { n: "01", t: "Install", d: "One npm line, or Cargo / Homebrew / a direct binary. On mainland China networks, the CNB and Tsinghua Tuna mirrors route around GitHub.", cta: "Install guide →", href: "/install" },
                { n: "02", t: "Add a key", d: "codewhale auth set --provider deepseek (or openrouter, anthropic, zai, …). A local vLLM or Ollama box needs no key at all.", cta: "Provider list →", href: "/docs#providers" },
                { n: "03", t: "Run it", d: "Type codewhale in a project. Plan mode is read-only by default; press Tab for Agent mode.", cta: "Docs →", href: "/docs" },
              ]
          ).map((item) => (
            <Link key={item.n} href={item.href} className="block p-6 hover:bg-paper-deep transition-colors">
              <div className="font-mono uppercase tracking-widest mb-2 text-[0.7rem] text-indigo">{item.n}</div>
              <h3 className="font-display text-xl mb-2">{item.t}</h3>
              <p className={`text-sm text-ink-soft mb-4 ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {item.d}
              </p>
              <span className="font-mono text-[0.7rem] uppercase tracking-widest text-indigo">{item.cta}</span>
            </Link>
          ))}
        </div>

        {/* ANY MODEL, HONESTLY — provider honesty, with live status folded in */}
        <div className="mt-10 px-4 py-3 hairline-t hairline-b hairline-l hairline-r text-sm leading-relaxed max-w-2xl space-y-1.5">
          <div className="eyebrow mb-1.5">{isZh ? "任意模型，实话实说" : "Any model, honestly"}</div>
          <p className={`text-xs text-ink-soft pb-1 ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
            {isZh
              ? `${facts.providers.length} 个提供商，同一个运行时。自带密钥，没有推理加价，不会悄悄换模型。此刻的真实情况：`
              : `${facts.providers.length} providers, one runtime. Bring your own key, no inference markup, no silent model switching. Where things stand right now:`}
          </p>
          {isZh ? (
            <>
              <div><span className="text-jade font-mono text-xs mr-2">✓</span>当前推荐：<span className="font-mono">GLM 5.2</span>，<span className="font-mono">high</span> reasoning，在 CodeWhale 里表现很好。</div>
              <div><span className="text-jade font-mono text-xs mr-2">✓</span>OpenAI Codex 登录可用。</div>
              <div><span className="text-ink-mute font-mono text-xs mr-2">✗</span>Kimi OAuth 暂时不可用，正在修。</div>
              <div className="pt-1 text-xs text-ink-mute flex flex-wrap gap-x-4 gap-y-1">
                <Link href="/zh/models" className="text-indigo hover:underline">全部提供商 →</Link>
                <span>没看到你想要的模型或端点？<a href="https://github.com/Hmbown/CodeWhale/issues/new" className="text-indigo hover:underline">开个 issue</a>。</span>
              </div>
            </>
          ) : (
            <>
              <div><span className="text-jade font-mono text-xs mr-2">✓</span>Recommended right now: <span className="font-mono">GLM 5.2</span> on <span className="font-mono">high</span> reasoning — working very well in CodeWhale.</div>
              <div><span className="text-jade font-mono text-xs mr-2">✓</span>OpenAI Codex login is working.</div>
              <div><span className="text-ink-mute font-mono text-xs mr-2">✗</span>Kimi OAuth is temporarily broken; on the list.</div>
              <div className="pt-1 text-xs text-ink-mute flex flex-wrap gap-x-4 gap-y-1">
                <Link href="/models" className="text-indigo hover:underline">All providers →</Link>
                <span>Don&apos;t see a model or endpoint you want? <a href="https://github.com/Hmbown/CodeWhale/issues/new" className="text-indigo hover:underline">Open an issue</a>.</span>
              </div>
            </>
          )}
        </div>
      </section>

      {/* WHAT'S GOING ON — activity + dispatch */}
      <section className="bg-paper-deep hairline-t hairline-b">
        <div className="mx-auto max-w-[1400px] px-6 py-14">
          <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
            <Seal char="动" />
            <h2 className="font-display">
              {isZh ? "最近在发生什么" : "What's going on"}
            </h2>
          </div>

          {/* Recent activity from the repo */}
          {feed.length > 0 && (
            <div className="mb-10">
              <div className="eyebrow mb-3">{isZh ? "仓库近期活动" : "Recent repo activity"}</div>
              <ul className="space-y-2">
                {feed.slice(0, 6).map((item) => (
                  <li key={`${item.url}-${item.number}`} className="flex items-baseline gap-3 text-sm">
                    <span className="font-mono text-[0.66rem] text-indigo uppercase tracking-widest w-10 shrink-0">
                      {item.kind === "pull" ? "PR" : "ISS"}
                    </span>
                    <span className="font-mono text-xs text-ink-mute tabular shrink-0">#{item.number}</span>
                    <a href={item.url} className="text-ink hover:text-indigo transition-colors">
                      {item.title.slice(0, 90)}{item.title.length > 90 ? "…" : ""}
                    </a>
                  </li>
                ))}
              </ul>
              <div className="mt-4">
                <Link href={isZh ? "/zh/feed" : "/feed"} className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                  {isZh ? "全部活动 →" : "All activity →"}
                </Link>
              </div>
            </div>
          )}

          {/* Today's dispatch */}
          <article className="grid lg:grid-cols-12 gap-x-10 gap-y-6 max-w-[1100px]">
            <h3 className="lg:col-span-12 font-display text-2xl sm:text-3xl leading-tight">
              {isZh && dispatch.headlineZh ? dispatch.headlineZh : dispatch.headline}
            </h3>
            <p className={`lg:col-span-7 text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
              {isZh && dispatch.summaryZh ? dispatch.summaryZh : dispatch.summary}
            </p>
            <ul className="lg:col-span-5 space-y-3">
              {highlights.slice(0, 3).map((h, i) => (
                <li key={i} className="flex items-baseline gap-3">
                  <span className="font-mono text-[0.66rem] text-indigo uppercase tracking-widest w-16 shrink-0">
                    {h.tag}
                  </span>
                  <div>
                    <Link href={h.href} className="body-link font-display text-base leading-snug">
                      {h.title}
                    </Link>
                    <p className={`text-sm text-ink-soft mt-0.5 ${isZh ? "leading-[1.8]" : ""}`}>{h.blurb}</p>
                  </div>
                </li>
              ))}
            </ul>
          </article>
        </div>
      </section>

      {/* GET HELP — where to look, especially for China network visitors */}
      <section className="mx-auto max-w-[1400px] px-6 py-14">
        <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
          <Seal char="助" />
          <h2 className="font-display">
            {isZh ? "需要帮助？" : "Need help?"}
          </h2>
        </div>

        <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
          {(isZh
            ? [
                { t: "安装与配置", d: "每种安装方式、密钥设置、沙箱、CNB / 清华 Tuna 国内镜像、常见报错排查。", cta: "安装指南 →", href: "/zh/install" },
                { t: "常见问题", d: "模型、提供商、模式、MCP、技能、配置文件位置等高频问题。", cta: "FAQ →", href: "/zh/faq" },
                { t: "提议题或 PR", d: "遇到 bug 或有想法，直接在 GitHub 开 issue 或 pull request。维护者会亲自看。", cta: "参与贡献 →", href: "/zh/contribute" },
              ]
            : [
                { t: "Install & configure", d: "Every install path, key setup, sandboxing, the CNB / Tsinghua Tuna mirrors for mainland China, and troubleshooting.", cta: "Install guide →", href: "/install" },
                { t: "FAQ", d: "High-frequency questions on models, providers, modes, MCP, skills, and where config lives.", cta: "FAQ →", href: "/faq" },
                { t: "File an issue or PR", d: "Hit a bug or have an idea? Open an issue or pull request on GitHub — the maintainer reads everything personally.", cta: "Contribute →", href: "/contribute" },
              ]
          ).map((item) => (
            <Link key={item.t} href={item.href} className="block p-6 hover:bg-paper-deep transition-colors">
              <h3 className="font-display text-xl mb-2">{item.t}</h3>
              <p className={`text-sm text-ink-soft mb-4 ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {item.d}
              </p>
              <span className="font-mono text-[0.7rem] uppercase tracking-widest text-indigo">{item.cta}</span>
            </Link>
          ))}
        </div>

        {/* Mirror strip — surfaced up where a stuck visitor will see it, not buried in the footer */}
        {isZh && (
          <div className="mt-8 hairline-t pt-6 flex flex-wrap items-baseline gap-x-6 gap-y-3">
            <div className="eyebrow shrink-0">{isZh ? "国内镜像 / China mirrors" : "China mirrors"}</div>
            <div className="flex flex-wrap gap-4 text-sm">
              <a href="https://cnb.cool/codewhale.net/codewhale" className="text-indigo hover:underline" target="_blank" rel="noopener">CNB 镜像</a>
              <a href="https://npmmirror.com/package/codewhale" className="text-indigo hover:underline" target="_blank" rel="noopener">npmmirror</a>
              <a href="https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index.html" className="text-indigo hover:underline" target="_blank" rel="noopener">清华 Tuna crates.io</a>
            </div>
            <p className="w-full text-xs text-ink-mute leading-relaxed max-w-2xl">
              {isZh
                ? "npm 安装时可设 CODEWHALE_USE_CNB_MIRROR=1，wrapper 会改从 CNB 下载二进制。DeepSeek API（api.deepseek.com）国内直连，无需代理。"
                : "Set CODEWHALE_USE_CNB_MIRROR=1 during npm install to fetch binaries from CNB. The DeepSeek API (api.deepseek.com) is reachable from mainland China without a proxy."}
            </p>
          </div>
        )}
      </section>

      {/* RELEASE CREDITS — the community that built this release */}
      <section id="release-credits" className="mx-auto max-w-[1400px] px-6 py-14">
        <div className="flex items-baseline gap-4 mb-5 hairline-b pb-4">
          <Seal char="谢" />
          <div>
            <div className="eyebrow mb-2">{isZh ? `v${facts.version} 致谢` : `v${facts.version} credits`}</div>
            <h2 className="font-display text-3xl">
              {isZh ? "每个补丁和报告都算数" : "Every patch and report counts"}
            </h2>
          </div>
        </div>
        <div className="grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-5">
            <p className={`text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
              {isZh
                ? "这一版合并和吸收了来自社区的大量工作。完整条目在 CHANGELOG 中；这里保留最新发布的公开致谢入口。"
                : "This release merged and harvested a large community tranche. The full notes live in the changelog; this keeps the latest public credit surface easy to find."}
            </p>
            <div className="flex flex-wrap gap-x-5 gap-y-2 mt-4">
              <Link href="https://github.com/Hmbown/CodeWhale/blob/main/docs/CONTRIBUTORS.md" className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "完整贡献者名单 →" : "Full contributor list →"}
              </Link>
              <Link href="https://github.com/Hmbown/CodeWhale/blob/main/CHANGELOG.md" className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "CHANGELOG →" : "CHANGELOG →"}
              </Link>
              <Link href={isZh ? "/zh/contribute" : "/contribute"} className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "参与贡献 →" : "Contribute →"}
              </Link>
              <Link href="https://github.com/Hmbown/CodeWhale/issues" className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "开放议题 →" : "Open issues →"}
              </Link>
            </div>
          </div>
          <div className="lg:col-span-7 grid gap-6">
            <div>
              <div className="eyebrow mb-3">{isZh ? "已合并 / 已吸收贡献" : "Merged and harvested contributions"}</div>
              <div className="flex flex-wrap gap-2">
                {RELEASE_CONTRIBUTORS.map((handle) => (
                  <Link
                    key={handle}
                    href={`https://github.com/${handle.slice(1)}`}
                    className="font-mono text-xs px-2 py-1 hairline-t hairline-b hairline-l hairline-r text-ink-soft hover:text-indigo hover:bg-paper-deep"
                  >
                    {handle}
                  </Link>
                ))}
              </div>
            </div>
            <div>
              <div className="eyebrow mb-3">{isZh ? "报告、复现和验证" : "Reports, repros, and verification"}</div>
              <div className="flex flex-wrap gap-2">
                {RELEASE_HELPERS.map((handle) => (
                  <Link
                    key={handle}
                    href={`https://github.com/${handle.slice(1)}`}
                    className="font-mono text-xs px-2 py-1 hairline-t hairline-b hairline-l hairline-r text-ink-soft hover:text-indigo hover:bg-paper-deep"
                  >
                    {handle}
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* WHAT IT DOESN'T DO — the boundaries, stated plainly */}
      <section className="mx-auto max-w-[1400px] px-6 py-14">
        <div className="flex items-baseline gap-4 mb-5 hairline-b pb-4">
          <Seal char="非" />
          <h2 className="font-display">{isZh ? "CodeWhale 不做什么" : "What CodeWhale doesn't do"}</h2>
        </div>
        <p className={`mb-8 text-ink-soft max-w-2xl ${isZh ? "leading-[1.9] tracking-wide" : "text-sm leading-relaxed"}`}>
          {isZh
            ? "有些边界值得写清楚。下面每一条都对这份代码库为真，可以在源码里核对——不是营销措辞。"
            : "Some boundaries are worth stating outright. Each line below is true of this codebase and checkable in the source — not a marketing turn of phrase."}
        </p>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
          {(isZh
            ? [
                { t: "不需要云账号", d: "在你的机器上本地运行，无需注册 CodeWhale 账号。本地 vLLM / Ollama 模型连密钥都不用。" },
                { t: "不收集你的代码", d: "你的代码和使用数据都留在本机，没有任何分析上报。唯一自发的网络请求是一个可关闭的新版本检查，不发送任何代码。" },
                { t: "不加推理差价", d: "自带密钥，请求直连你配置的提供商，按提供商的价格计费。没有中间代理，没有加价。" },
                { t: "不要求 CLA", d: "贡献即 MIT 进、MIT 出。没有贡献者许可协议，也不需要签署版权转让。" },
                { t: "不悄悄换模型", d: "你选的模型就是运行的模型。切换是显式命令；自动路由需手动开启，并会显示所选路由。" },
                { t: "法典越不过运行时控制", d: "审批、沙箱、网络与信任由代码强制执行。任何法典文本——内置的、你的、或仓库的——都无法放松它们。" },
              ]
            : [
                { t: "No cloud account", d: "It runs locally on your machine — no CodeWhale account, no sign-up. A local vLLM or Ollama model needs no key at all." },
                { t: "No code telemetry", d: "Your code and usage stay on your machine; nothing is sent for analytics. The only call it makes on its own is an opt-out check for a newer release, which sends no code." },
                { t: "No inference markup", d: "Bring your own key. Requests go straight to the provider you configured, at the provider's price. No proxy, no margin." },
                { t: "No CLA", d: "Contributing is MIT in, MIT out. There is no contributor license agreement and no copyright assignment to sign." },
                { t: "No silent model switching", d: "The model you pick is the model that runs. Switching is an explicit command; automatic routing is opt-in and shown." },
                { t: "Constitution can't override runtime controls", d: "Approval, sandbox, network, and trust are enforced in code. No constitution text — bundled, yours, or a repo's — can loosen them." },
              ]
          ).map((item) => (
            <div key={item.t} className="p-6">
              <div className="flex items-baseline gap-2 mb-2">
                <span className="font-mono text-xs text-ink-mute shrink-0 mt-0.5">✗</span>
                <h3 className="font-display text-lg leading-snug">{item.t}</h3>
              </div>
              <p className={`text-sm text-ink-soft pl-5 ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {item.d}
              </p>
            </div>
          ))}
        </div>
        <p className="mt-5 text-xs text-ink-mute leading-relaxed max-w-xl">
          {isZh ? (
            <>
              最后一条是根本性的，而且可验证——由执行框架的代码强制生效。{" "}
              <Link href={isZh ? "/zh/constitution" : "/constitution"} className="text-indigo hover:underline">阅读宪法 →</Link>
            </>
          ) : (
            <>
              The last one is load-bearing and verifiable — enforced in the harness code, not the prose.{" "}
              <Link href={isZh ? "/zh/constitution" : "/constitution"} className="text-indigo hover:underline">Read the constitution →</Link>
            </>
          )}
        </p>
      </section>

      {/* JOIN IN — the project is the point */}
      <section className="bg-ink text-paper">
        <div className="mx-auto max-w-[1400px] px-6 py-20 grid lg:grid-cols-12 gap-10 items-center">
          <div className="lg:col-span-8">
            <div className="eyebrow text-paper-deep/70 mb-3">{isZh ? "这个项目" : "The project"}</div>
            <h2 className="font-display text-paper text-4xl leading-tight">
              {isZh ? "来自世界各地的开发者，把 CodeWhale 变成了今天的样子。" : "Developers from all over have made CodeWhale what it is."}
            </h2>
            <p className={`mt-5 text-paper-deep/80 max-w-2xl ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "CodeWhale 起于一个人的 DeepSeek 业余项目，来自许多国家的贡献者把它塑造成了现在的样子——每一版发布上的贡献者名单就是证据。这里没有 CLA，没有赞助商优先通道，议题公开分类，版本从 main 分支发布。"
                : "CodeWhale started as one person's DeepSeek side project, and contributors from many countries have shaped it into what it is — the contributor list on every release is the proof. No CLA, no sponsor lockouts, issues triaged in the open, releases cut from main."}
            </p>
            <blockquote className={`mt-6 pl-4 border-l-2 border-indigo text-paper-deep/90 max-w-2xl ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "「所有反馈都是礼物。」——这是我教书时很早就学到的一句话，也是我维护 CodeWhale 的方式。每一个 issue、PR、bug 报告或想法，都是我理解真实使用场景、做出更好决策的方式。"
                : "“All feedback is a gift.” Something I learned early in teaching, and the way I maintain CodeWhale. Every issue, PR, bug report, or idea is how I understand real use cases and make better decisions."}
            </blockquote>
            <p className={`mt-4 text-paper-deep/70 max-w-2xl text-sm ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "如果你遇到用不了的地方，或者想要一个没列出来的模型——那是你能告诉这个项目的最有用的事。"
                : "If you hit something that doesn't work, or want a model that isn't listed — that's the most useful thing you can tell the project."}
            </p>
            <div className="mt-6 flex flex-wrap items-center gap-3">
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="px-4 py-2 hairline-t hairline-b hairline-l hairline-r border-white/20 text-paper font-mono text-sm hover:bg-white/10 transition-colors"
              >
                ★ {isZh ? "在 GitHub 上 Star" : "Star on GitHub"}
              </Link>
              <Link
                href="https://github.com/Hmbown/CodeWhale/issues/new"
                className="px-4 py-2 bg-indigo text-paper font-mono text-sm hover:bg-indigo-deep transition-colors"
              >
                {isZh ? "开个 issue →" : "Open an issue →"}
              </Link>
              <Link
                href={isZh ? "/zh/contribute" : "/contribute"}
                className="px-4 py-2 font-mono text-sm text-paper-deep/80 hover:text-paper transition-colors"
              >
                {isZh ? "参与贡献 →" : "Contribute →"}
              </Link>
            </div>
          </div>

          <div className="lg:col-span-4 font-mono text-sm text-paper-deep/80 space-y-2">
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "版本" : "version"}</span>
              <span className="tabular text-paper">{facts.version ?? "v0.8.x"}</span>
            </div>
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "提供商" : "providers"}</span>
              <span className="tabular text-paper">{facts.providers.length}</span>
            </div>
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "许可证" : "license"}</span>
              <span className="text-paper">{facts.license ?? "MIT"}</span>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
